// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RecipeAssignment.Models;
using System;

namespace RecipeAssignment.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191114021132_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RecipeAssignment.Models.Recipe", b =>
                {
                    b.Property<string>("RecipeName")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Directions");

                    b.Property<string>("Ingredients");

                    b.Property<string>("Rating");

                    b.Property<string>("RatingReview");

                    b.HasKey("RecipeName");

                    b.ToTable("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
